server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://106.15.72.234/leyou?serverTimezone=UTC
    username: root
    password: 981204
  rabbitmq:
    host: 106.15.72.234
    virtual-host: /leyou
    username: leyou
    password: leyou
    template:
      exchange: LEYOU.ITEM.EXCHANGE
    publisher-confirms: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5  # 5秒钟发送一次心跳
    lease-expiration-duration-in-seconds: 15 # 15秒不发送就过期
mybatis:
  type-aliases-package: com.leyou.item.pojo
