server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://106.15.72.234:3306/leyou?serverTimezone=UTC
    username: root
    password: 981204
  redis:
    host: 106.15.72.234
  rabbitmq:
    virtual-host: /leyou
    host: 106.15.72.234
    username: leyou
    password: leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
mybatis:
  type-aliases-package: com.leyou.user.pojo
